config/routes.rb
Sandboxy::Application.routes.draw do

  devise_for :users

  match 'ApiUsers' => 'api_users#index', :via => [:get], :as => 'api_users_list'
  match 'ApiUsers/new' => 'api_users#new', :via => [:get], :as => 'new_api_user'
  match 'ApiUsers/create' => 'api_users#create', :via => [:post], :as => "api_users"
  match 'ApiUsers/destroy/:id' => 'api_users#destroy', :via => [:delete], :as => "delete_api_users"

  resource :links
  match 'links/get_links' => 'links#get_links', :via => [:post], :as => "get_links_by_group"

  root :to => 'home#index'

  match 'datarequest/test_auth', :via => [:post]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end

end

app/models/api_user.rb
class ApiUser < ActiveRecord::Base

  attr_accessible :id, :usr_name, :enc_pswd, :api_key, :is_active, :created_at

  validates_presence_of :usr_name, :enc_pswd

  scope :simple_list, select("id, usr_name, api_key, is_active, created_at")
end

app/models/crumb.rb
class Crumb
  def initialize(text, link)
    @text = text
    @link = link
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :id, :title, :url, :description
  validates_presence_of :title, :url

  has_and_belongs_to_many :link_groups, :uniq => true, :join_table => :grouped_links

  scope :simple_list, select("id, usr_name, api_key, is_active, created_at")
end

app/models/link_group.rb
class LinkGroup < ActiveRecord::Base
  has_and_belongs_to_many :links, :uniq => true, :join_table => :grouped_links
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :rememberable
end

app/controllers/api_users_controller.rb
class ApiUsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @data = ApiUser.simple_list
  end

  def new
    @api_user = ApiUser.new
  end

  def create

    @api_user = ApiUser.new(params[:api_user])
    if @api_user.save
      flash[:notice] = "API User added."

      # sends a 302 redirect request to the browser,
      # any existing variables are lost,
      # and the specified action will be executed

      redirect_to :action => 'index'
    else

      # will NOT execute the code in the specified action.
      # It will render the view only. Existing variables will not be lost.

      render :action => 'new'
    end

  end

  def destroy

    deleteMe = ApiUser.find(params[:id])
    if deleteMe
       deleteMe.destroy
    end

    respond_to do |format|
      format.html { redirect_to :action => 'index' }
      format.xml  { head :ok }
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  @crumbs
  def index
  end

end

app/controllers/datarequest_controller.rb
class DatarequestController < ActionController::Base

  def test_auth

    _response = format_error("Not Authorized", 100)

    # credential string: user:pswd
    if valid_credentials(request.headers['Auth123'])
      _response = valid_request(request.raw_post)
    end
    respond_to do |format|
      format.xml { render :xml => "#{_response}" }
      format.any  {render :text => "Only JSON and XML are currently supported"}
    end

  end

  private

  def valid_request(xml)

    rv = format_error("Bad Request", 200)
    if xml && !xml.empty?
       rv = "Ok"
    end
    rv

  end

  def valid_credentials(cred_token)

    rv = false
    if cred_token && !cred_token.empty?
      creds = cred_token.split(':')
      if creds && creds.count == 2
        rv = true
      end
    end
    rv

  end

  def format_error(msg, code)
    xm = ::Builder::XmlMarkup.new
    xm.error("code" => "#{code}") { |x| msg }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  def index
    @crumbs ||= []
    @crumbs << Crumb.new("Home", "")
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @crumbs << Crumb.new("Links", "")
  end

  def show
    if !@selectedGroup || @selectedGroup <= 0
      @groups = LinkGroup.all
    end
  end

  def get_links
    @selectedGroup = params[:group]
    @groups = LinkGroup.all
    #_grp = LinkGroup.find(@selectedGroup)
    @group_links = (@selectedGroup != '1') ? Link.find(:all, :include => :link_groups, :conditions => {"grouped_links.link_group_id" => @selectedGroup}) : Link.all
    render :action => 'show'
  end

  def new
  end

  def edit
  end

  def update
  end

  def create
  end

  def destroy
  end

end

app/helpers/api_users_helper.rb
require 'time'

module ApiUsersHelper

  def DateFormat(date)
      #dt = Time.parse(date)
      date.strftime("%m/%d/%Y - %I:%M%p")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/api_users/_form.html.erb
<%= form_for(@api_user) do |f| %>
  <% if @api_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_user.errors.count, "error") %> prohibited this Api User from being saved:</h2>

      <ul>
      <% @api_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fieldContainer">
    <div class="fieldLabel">
        <%= f.label :usr_name, 'User Name'%>
    </div>
    <div class="field">
        <%= f.text_field :usr_name %>
    </div>
  </div>

  <div class="fieldContainer">
    <div class="fieldLabel">
        <%= f.label :enc_pswd, 'Password' %>
    </div>
    <div class="field">
        <%= f.text_field :enc_pswd %>
    </div>
  </div>

  <div class="fieldContainer">
    <div class="fieldLabel">
        <%= f.label :api_key, 'API Key' %>
    </div>
    <div class="field">
        <%= f.text_field :api_key %>
    </div>
  </div>

  <div class="fieldContainer">
    <div class="fieldLabel">
        <%= f.label :is_active, 'Active?' %>
    </div>
    <div class="field">
        <%= f.check_box :is_active, :id => "is_active", :class => "allows_dependent_fields" %>
    </div>
  </div>

  <div class="fieldContainer">
    <%= f.submit  "Add" %>
  </div>



<% end %>

app/views/api_users/index.haml
= content_for :left_nav do
 - render :partial => "home/nav", :locals => { :context => 'API' }

= content_for :main do

 %p
  %div API User Snapshot.

  - if @data != nil && @data.count > 0
   %table{ :border => "1", :width => "500", :cellpadding => "2", :cellspacing => "0" }
    %tbody
     - @data.each do |maprow|
      %tr
       - [maprow.usr_name, maprow.api_key, maprow.is_active].each do |mapcol|
        %td= mapcol
       %td
        = link_to 'Delete', delete_api_users_path(:id => maprow.id), :confirm => 'Are you sure?', :method => :delete
  - else
   %p No API users defined.

  %p
   = link_to 'Add Api User', new_api_user_path

  %p
   = link_to "Back", :root

app/views/api_users/new.haml
= render 'form'

= link_to 'Back', :back

app/views/home/_nav.haml
%ul{:class => 'nav_container'}
 - link_titles = {'News Port' => root_path, 'API User Administration' => api_users_list_path, 'Linkster' => links_path, 'Notebook' => root_path, 'Gallery' => root_path}
 - link_titles.each do |k,v|
  %li{:class => 'nav_item'}
  = link_to k, v

app/views/home/index.haml
= content_for :left_nav do
 - render :partial => "home/nav", :locals => { :context => 'NEWS' }

= content_for :main do
 - render :partial => "news/feeds"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-color: #000000;">
<head>
  <title>Sandboxy</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "sassy" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

<% if user_signed_in? %>

    <div class="container top_container">
        <div class="login_state">
         Logged in as '<%= current_user.username %>'.&nbsp;&nbsp;<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
        </div>
      <div class="notifier">
          <%= image_tag "BgallaMask.png", :alt => "B\'galla!" %>
      </div>
        <div class="notifier bigtext">
           <pre>Willkommen in der Dunkleheit</pre>
        </div>
    </div>

    <div class="container top_container">
       <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
       <% end %>
     </div>

    <div class="container top_container">
        <div class="nav_options">
            <%= yield :left_nav %>
        </div>
        <div class="main">
            <%= yield :main %>
        </div>
    </div>

<% else %>
    <%= yield %>
<% end %>

</body>
</html>

app/views/links/_groups.haml
= form_tag get_links_by_group_path do
  %div
    Groups:
    = select_tag :group, options_from_collection_for_select(@groups,"id","title",(@selectedGroup) ? @selectedGroup : 0)
    = submit_tag "Show"

app/views/links/index.haml
%p
 Index

app/views/links/show.haml
= content_for :left_nav do
 - render :partial => "home/nav", :locals => { :context => 'LINKS' }

= content_for :main do
 = form_tag get_links_by_group_path do
  %div
   Groups:
   = select_tag :group, options_from_collection_for_select(@groups,"id","title",(@selectedGroup) ? @selectedGroup : 0)
   = submit_tag "Show"

  - if @group_links
   - if @group_links.count > 0
    %table{ :border => "1", :width => "500", :cellpadding => "2", :cellspacing => "0" }
     %tbody
      - @group_links.each do |maprow|
       %tr
       - [maprow.title, maprow.url].each do |mapcol|
        %td= mapcol
       %td
        = link_to 'Delete', delete_api_users_path(:id => maprow.id), :confirm => 'Are you sure?', :method => :delete
   - else
    %p
     No links found for that group.

app/views/news/_feeds.haml
%d
 News feeds